services:
  goCrawlDeeplDev:
    container_name: goCrawlDevtainer
    image: crawl-deepl:dev
    build: 
      context: .
      target: dev
    volumes:
      - ./app:/usr/src/app
      - go-build-cache:/root/.cache/go-build
      - go-modules:/go/pkg/mod
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      CHAT_ID: ${CHAT_ID}
      FROM_LANGUAGE: ${FROM_LANGUAGE}
      TO_LANGUAGE: ${TO_LANGUAGE}
    entrypoint: ["tail", "-f", "/dev/null"]

  webServer:
    container_name: webServerDevtainer
    image: crawl-deepl-test-display-server:dev
    build:
      context: ./app_for_test_display
    volumes:
      - ./app/test_coverage/:/test_coverage
    ports:
      - 8080:8080
    environment:
      PORT: 8080

volumes:
  go-build-cache:
  go-modules:
